import { objectSchema, id, ref, integer } from './tool-schema.js';

export const CORE_TOOLS = Object.freeze([
  {
    name: 'ohos_host_register',
    description: 'Register or refresh a verified host binding. Parent/controller use only.',
    principals: ['parent', 'all'],
    inputSchema: objectSchema({
      binding_id: id,
      host_kind: { type: 'string', enum: ['codex', 'claude-code', 'cursor', 'trae', 'other'] },
      host_version: { type: 'string', maxLength: 128 },
      execution_mode: { type: 'string', enum: ['host_native', 'external'], default: 'host_native' },
      capabilities: { type: 'object', additionalProperties: { type: 'boolean' } },
      capability_source: { type: 'string', minLength: 1, maxLength: 256 },
      idempotency_key: id,
    }, ['binding_id', 'host_kind', 'capabilities', 'capability_source', 'idempotency_key']),
    invoke: (controller, args, principal) => controller.registerHost(args, principal),
  },
  {
    name: 'ohos_host_capabilities',
    description: 'Read the recorded capabilities and execution mode for a host binding.',
    principals: ['parent', 'worker', 'all'],
    inputSchema: objectSchema({ binding_id: id }, ['binding_id']),
    invoke: (controller, args) => controller.hostCapabilities(args),
  },
  {
    name: 'ohos_run_status',
    description: 'Read durable workflow state and bounded events after an optional cursor.',
    principals: ['parent', 'worker', 'all'],
    inputSchema: objectSchema({ run_id: id, cursor: integer }, ['run_id']),
    invoke: (controller, args) => controller.runStatus(args),
  },
  {
    name: 'ohos_task_claim',
    description: 'Atomically lease the next task for one role and receive a scoped task credential.',
    principals: ['worker', 'all'],
    inputSchema: objectSchema({
      run_id: id,
      role: id,
      host_binding_id: id,
      context_id: id,
      expected_revision: { type: 'integer', minimum: 1 },
      idempotency_key: id,
    }, ['run_id', 'role', 'host_binding_id', 'expected_revision', 'idempotency_key']),
    invoke: (controller, args) => controller.claimTask(args),
  },
  {
    name: 'ohos_task_heartbeat',
    description: 'Renew an active task lease and observe a pending cancellation request.',
    principals: ['worker', 'all'],
    inputSchema: objectSchema({
      attempt_id: id,
      lease_epoch: { type: 'integer', minimum: 1 },
      task_credential: { type: 'string', minLength: 1, maxLength: 512 },
    }, ['attempt_id', 'lease_epoch', 'task_credential']),
    invoke: (controller, args) => controller.heartbeatTask(args),
  },
  {
    name: 'ohos_task_context',
    description: 'Read the scoped input and output references for an already leased task.',
    principals: ['worker', 'all'],
    inputSchema: objectSchema({
      attempt_id: id,
      lease_epoch: { type: 'integer', minimum: 1 },
      task_credential: { type: 'string', minLength: 1, maxLength: 512 },
    }, ['attempt_id', 'lease_epoch', 'task_credential']),
    invoke: (controller, args) => controller.taskContext(args),
  },
  {
    name: 'ohos_task_submit',
    description: 'Submit produced artifact references for deterministic validation. This never grants PASS.',
    principals: ['worker', 'all'],
    inputSchema: objectSchema({
      attempt_id: id,
      revision: { type: 'integer', minimum: 1 },
      lease_epoch: { type: 'integer', minimum: 1 },
      task_credential: { type: 'string', minLength: 1, maxLength: 512 },
      artifact_refs: { type: 'array', minItems: 1, maxItems: 100, items: ref },
      summary: { type: 'string', minLength: 1, maxLength: 4096 },
      idempotency_key: id,
    }, ['attempt_id', 'revision', 'lease_epoch', 'task_credential',
      'artifact_refs', 'summary', 'idempotency_key']),
    invoke: (controller, args) => controller.submitTask(args),
  },
  {
    name: 'ohos_task_release',
    description: 'Release unfinished work; partial artifacts force reconciliation before another writer.',
    principals: ['worker', 'all'],
    inputSchema: objectSchema({
      attempt_id: id,
      lease_epoch: { type: 'integer', minimum: 1 },
      task_credential: { type: 'string', minLength: 1, maxLength: 512 },
      reason: { type: 'string', minLength: 1, maxLength: 1024 },
      artifact_refs: { type: 'array', maxItems: 100, items: ref },
      idempotency_key: id,
    }, ['attempt_id', 'lease_epoch', 'task_credential', 'reason', 'idempotency_key']),
    invoke: (controller, args) => controller.releaseTask(args),
  },
]);
