#!/usr/bin/env python3
# Copyright (c) 2026. Licensed under the Apache License, Version 2.0.
"""
refresh_todo.py — regenerate <pipeline-dir>/todo.md from AR_design.md + state.

The orchestrator runs this at the START of every scheduling loop so todo.md
always reflects the current phase and derives concrete per-phase items from the
signed design doc. todo.md is the on-disk mirror (for resume); the orchestrator
also mirrors the same items into TodoWrite for in-session visibility.

No third-party deps. Degrades gracefully: if AR_design.md is absent (legacy run)
it still emits the global phase progress.
"""
import argparse
import json
import os
import re
import sys

PHASE_LABELS = [
    (0, "P0 环境初始化"),
    (1, "P1 设计固化 + 代码开发"),
    (2, "P2 编译验证"),
    (3, "P3 测试用例编写与验证"),
    (4, "P4 真机功能测试"),
    (5, "P5 质量验证"),
    (6, "P6 上库 review"),
]


def _split_md_sections(text):
    lines = text.splitlines()
    heads = [(i, len(m.group(1)), ln) for i, ln in enumerate(lines)
             for m in [re.match(r"^\s*(#{1,6})\s+\S", ln)] if m]
    out = []
    for hi, (idx, level, line) in enumerate(heads):
        end = len(lines)
        for j in range(hi + 1, len(heads)):
            if heads[j][1] <= level:
                end = heads[j][0]
                break
        out.append((line, "\n".join(lines[idx + 1:end])))
    return out


def _section_items(text, keywords, limit=12):
    """Bullet/numbered lines under the first section whose heading matches."""
    for head, body in _split_md_sections(text or ""):
        if any(k in head for k in keywords):
            items = []
            for ln in body.splitlines():
                s = ln.strip()
                m = re.match(r"^(?:[-*]|\d+[.)])\s+(.*)$", s)
                if m and m.group(1).strip():
                    items.append(m.group(1).strip())
            return items[:limit]
    return []


def build_todo(state, design_text, entries):
    run_id = state.get("run_id", "")
    cur = state.get("current_phase", 0)
    status = {p["id"]: p.get("status", "pending") for p in state.get("phases", [])}
    lines = ["<!-- generated by refresh_todo.py; do not hand-edit -->",
             "# TODO — %s" % run_id, "",
             "当前阶段: **P%d**" % cur, "", "## 阶段进度"]
    for pid, label in PHASE_LABELS:
        mark = "x" if status.get(pid) == "passed" else " "
        arrow = "  ⬅ 当前" if pid == cur else ""
        lines.append("- [%s] %s%s" % (mark, label, arrow))

    if design_text:
        lines += ["", "## 本次设计派生细项(来自 AR_design.md)"]
        files = _section_items(design_text, ["文件清单", "文件列表", "file list"])
        points = _section_items(design_text, ["需测试", "功能点", "test point"])
        cases = _section_items(design_text, ["真机", "用例构造", "test case"])
        if files:
            lines.append("### 计划实现文件 (P1)")
            lines += ["- [ ] 实现 `%s`" % f for f in files]
        if points:
            lines.append("### 需测试的功能点 (P3/P5)")
            lines += ["- [ ] 覆盖: %s" % p for p in points]
        if cases:
            lines.append("### 真机用例构造 (P4)")
            lines += ["- [ ] 真机验证: %s" % c for c in cases]
    else:
        lines += ["", "> 无 AR_design.md(legacy run)——仅显示阶段进度。"]

    nxt = {0: "跑 gate_env_init 后 advance --phase 0",
           1: "先 gate_design.py(AR_design)→ 写代码 → gate_develop.py → advance --phase 1",
           2: "gate_build.py → advance --phase 2",
           3: "gate_test_ut.py(只增独立测试)→ advance --phase 3",
           4: "gate_device_func.py → 人工 consent → advance --phase 4",
           5: "gate_integration.py + 质量报告 → 人工 consent → advance --phase 5",
           6: "gate_upload_ci.py(两份 review + PR + CI)→ 人工 consent → advance --phase 6"}
    lines += ["", "## 下一步", "- %s" % nxt.get(cur, "见编排器 SKILL.md")]
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser(description="regenerate todo.md from AR_design + state")
    ap.add_argument("--pipeline-dir", required=True)
    args = ap.parse_args()
    pdir = os.path.abspath(args.pipeline_dir)
    with open(os.path.join(pdir, "pipeline.json"), encoding="utf-8") as f:
        state = json.load(f)
    design_text = None
    for cand in ("evidence/phase1/AR_design.md", "AR_design.md"):
        p = os.path.join(pdir, cand)
        if os.path.isfile(p):
            with open(p, encoding="utf-8", errors="replace") as f:
                design_text = f.read()
            break
    entries = []
    mp = os.path.join(pdir, "evidence", "manifest.jsonl")
    if os.path.exists(mp):
        with open(mp, encoding="utf-8") as f:
            entries = [json.loads(l) for l in f if l.strip()]
    todo = build_todo(state, design_text, entries)
    with open(os.path.join(pdir, "todo.md"), "w", encoding="utf-8") as f:
        f.write(todo)
    print("refreshed %s/todo.md (current_phase=%d, design=%s)"
          % (pdir, state.get("current_phase", 0), "yes" if design_text else "no"))


if __name__ == "__main__":
    main()
